import { Trip } from './trip';
export const TRIPS: Trip[] = [
  {
    name: 'Name',
    countryOfDestination: 'country of destination',
    startDate: new Date(),
    endDate: new Date(),
    price: 6123,
    spotsSelected: 0,
    spotsAvailable: 1,
    spotsMax: 38073,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto debitis quo iste libero vel perspiciatis veniam.',
    imgLink: 'https://dummyimage.com/200x200/ff7300/ffffff.jpg&text=wycieczka',
  },
  {
    name: 'Name',
    countryOfDestination: 'country of destination',
    startDate: new Date(),
    endDate: new Date(),
    price: 6412,
    spotsSelected: 0,
    spotsAvailable: 38073,
    spotsMax: 38073,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto debitis quo iste libero vel perspiciatis veniam.',
    imgLink: 'https://dummyimage.com/200x200/ff7300/ffffff.jpg&text=wycieczka',
  },
  {
    name: 'Name',
    countryOfDestination: 'country of destination',
    startDate: new Date(),
    endDate: new Date(),
    price: 4123,
    spotsSelected: 0,
    spotsAvailable: 2121,
    spotsMax: 38073,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto debitis quo iste libero vel perspiciatis veniam.',
    imgLink: 'https://dummyimage.com/200x200/ff7300/ffffff.jpg&text=wycieczka',
  },
  {
    name: 'Name',
    countryOfDestination: 'country of destination',
    startDate: new Date(),
    endDate: new Date(),
    price: 623,
    spotsSelected: 0,
    spotsAvailable: 2121,
    spotsMax: 38073,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto debitis quo iste libero vel perspiciatis veniam.',
    imgLink: 'https://dummyimage.com/200x200/ff7300/ffffff.jpg&text=wycieczka',
  },
  {
    name: 'Name',
    countryOfDestination: 'country of destination',
    startDate: new Date(),
    endDate: new Date(),
    price: 641,
    spotsSelected: 0,
    spotsAvailable: 2121,
    spotsMax: 38073,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto debitis quo iste libero vel perspiciatis veniam.',
    imgLink: 'https://dummyimage.com/200x200/ff7300/ffffff.jpg&text=wycieczka',
  },
  {
    name: 'Name',
    countryOfDestination: 'country of destination',
    startDate: new Date(),
    endDate: new Date(),
    price: 64,
    spotsSelected: 0,
    spotsAvailable: 2121,
    spotsMax: 38073,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto debitis quo iste libero vel perspiciatis veniam.',
    imgLink: 'https://dummyimage.com/200x200/ff7300/ffffff.jpg&text=wycieczka',
  },
  {
    name: 'Name',
    countryOfDestination: 'country of destination',
    startDate: new Date(),
    endDate: new Date(),
    price: 623,
    spotsSelected: 0,
    spotsAvailable: 2121,
    spotsMax: 38073,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto debitis quo iste libero vel perspiciatis veniam.',
    imgLink: 'https://dummyimage.com/200x200/ff7300/ffffff.jpg&text=wycieczka',
  },
  {
    name: 'Name',
    countryOfDestination: 'country of destination',
    startDate: new Date(),
    endDate: new Date(),
    price: 6123,
    spotsSelected: 0,
    spotsAvailable: 2121,
    spotsMax: 38073,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto debitis quo iste libero vel perspiciatis veniam.',
    imgLink: 'https://dummyimage.com/200x200/ff7300/ffffff.jpg&text=wycieczka',
  },
];
